server {
    # Listen on port 8080 (Cloud Run default)
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Handle Flutter web routing properly
        try_files $uri $uri/ /index.html;
    }
}
